// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM_vsETG6OuoTeEBja1cBbqXEXwPu2msQ',
    appId: '1:28316306727:web:f01832821699345362ad02',
    messagingSenderId: '28316306727',
    projectId: 'devchat-ff66e',
    authDomain: 'devchat-ff66e.firebaseapp.com',
    storageBucket: 'devchat-ff66e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU9z5tb6kEo95CxfuHiGuc1rqWyFAIhxQ',
    appId: '1:28316306727:android:ffde8e37a81ecc7b62ad02',
    messagingSenderId: '28316306727',
    projectId: 'devchat-ff66e',
    storageBucket: 'devchat-ff66e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc3hOTuesqFPYGPZAxsSUbq6zfD-0N_Ug',
    appId: '1:28316306727:ios:73321a22c13179c362ad02',
    messagingSenderId: '28316306727',
    projectId: 'devchat-ff66e',
    storageBucket: 'devchat-ff66e.appspot.com',
    iosClientId: '28316306727-d5k5s1chuae2tlpm07u6avqlui3o7ui9.apps.googleusercontent.com',
    iosBundleId: 'com.example.devchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc3hOTuesqFPYGPZAxsSUbq6zfD-0N_Ug',
    appId: '1:28316306727:ios:73321a22c13179c362ad02',
    messagingSenderId: '28316306727',
    projectId: 'devchat-ff66e',
    storageBucket: 'devchat-ff66e.appspot.com',
    iosClientId: '28316306727-d5k5s1chuae2tlpm07u6avqlui3o7ui9.apps.googleusercontent.com',
    iosBundleId: 'com.example.devchat',
  );
}
